// ═══════════════════════════════════════
// GRIM PORTFOLIO — data.js
// Generated by admin.html on 3/9/2026, 7:48:54 PM
// ═══════════════════════════════════════

const GRIM_DATA = {
  "identity": {
    "handle": "GRIM",
    "realname": "Shefan Tharani",
    "role": "Systems Engineer // Security Researcher",
    "tagline": "Building infrastructure. Exploiting systems. Securing what matters.",
    "github": "grim-sudo",
    "platform": "Arch / Kali / Debian",
    "toolset": "BlackArch · Metasploit · Burp Suite",
    "shell": "zsh / bash",
    "location": "CLASSIFIED",
    "clearance": "CLASSIFIED",
    "available": true
  },
  "mission": {
    "overview": "Systems engineer and security researcher specializing in Linux infrastructure, container orchestration, and offensive security operations.\n\nExperienced in designing and operating resilient systems while exploring attack surfaces across modern infrastructure. Works extensively with containerized environments, network architectures, and security testing methodologies.\n\nOperates at the intersection of DevOps engineering and adversarial security research, combining infrastructure development with offensive security experimentation to better understand and secure complex systems.",
    "platforms": [
      "Arch Linux",
      "Kali Linux",
      "Debian",
      "BlackArch",
      "Ubuntu Server",
      "Unix-like Systems"
    ],
    "focusAreas": [
      "Penetration Testing",
      "Open Source Intelligence (OSINT)",
      "Network Reconnaissance & Enumeration",
      "Linux Systems Engineering & Kernel Development",
      "Offensive Security Labs & CTF Operations"
    ],
    "toolset": [
      "Metasploit",
      "Burp Suite",
      "Nmap",
      "Docker",
      "Kubernetes",
      "Shodan",
      "Amass",
      "IPGhost",
      "Sherlock",
      "Zsteg",
      "SQLMap",
      "Maltego",
      "TheHarvester",
      "Gobuster",
      "Nikto"
    ]
  },
  "boot": {
    "lines": [
      {
        "t": "[  0.000000] Linux kernel 6.6.30-arch1 detected",
        "c": ""
      },
      {
        "t": "[  0.001201] Arch system profile loaded",
        "c": "ok"
      },
      {
        "t": "[  0.082410] BlackArch toolkit mounted — 2900 tools ready",
        "c": "ok"
      },
      {
        "t": "[  0.213800] Kali pentest modules loaded",
        "c": "ok"
      },
      {
        "t": "[  0.881100] NET: Registered PF_INET6 protocol family",
        "c": ""
      }
    ],
    "accessMessage": "ACCESS GRANTED"
  },
  "network": {
    "nodes": [
      {
        "id": "inet",
        "label": "INTERNET",
        "col": "#888888",
        "info": "External network. Untrusted traffic ingress."
      },
      {
        "id": "fw",
        "label": "FIREWALL",
        "col": "#ff3b3b",
        "info": "iptables + pfSense perimeter firewall. DPI enabled."
      },
      {
        "id": "router",
        "label": "ROUTER",
        "col": "#00d4ff",
        "info": "Edge router. BGP/OSPF routing with VLAN segmentation."
      },
      {
        "id": "devops",
        "label": "DEVOPS",
        "col": "#00d4ff",
        "info": "Infrastructure automation. CI/CD pipelines and container orchestration."
      },
      {
        "id": "dev",
        "label": "DEV",
        "col": "#00ff88",
        "info": "Application development stack. React, Node.js, Firebase."
      },
      {
        "id": "sec",
        "label": "SECURITY",
        "col": "#ff3b3b",
        "info": "Pentesting environment and offensive security tooling."
      },
      {
        "id": "kali",
        "label": "KALI BOX",
        "col": "#ff3b3b",
        "info": "Kali Linux attack node with Metasploit, Burp Suite and recon tools."
      },
      {
        "id": "db",
        "label": "DATABASE",
        "col": "#00ff88",
        "info": "Primary data store. PostgreSQL with encrypted backups."
      },
      {
        "id": "k8s",
        "label": "K8S CLUSTER",
        "col": "#00d4ff",
        "info": "Kubernetes cluster secured with Calico network policies."
      },
      {
        "id": "mon",
        "label": "MONITORING",
        "col": "#888888",
        "info": "Prometheus metrics collection with Grafana dashboards."
      }
    ]
  },
  "socials": [
    {
      "platform": "github",
      "label": "GitHub",
      "url": "https://github.com/grim-sudo",
      "icon": "github"
    },
    {
      "platform": "linkedin",
      "label": "LinkedIn",
      "url": "https://linkedin.com/in/shefan-tharani",
      "icon": "linkedin"
    },
    {
      "platform": "discord",
      "label": "Discord",
      "url": "https://discord.com/users/563804599119773708",
      "icon": "discord"
    },
    {
      "platform": "email",
      "label": "Email",
      "url": "mailto:shefantharani42@gmail.com",
      "icon": "mail"
    },
    {
      "platform": "instagram",
      "label": "Instagram",
      "url": "https://instagram.com/grim_756",
      "icon": "instagram"
    }
  ],
  "skills": [
    {
      "category": "programming",
      "items": [
        {
          "name": "C",
          "level": 85
        },
        {
          "name": "Python",
          "level": 90
        },
        {
          "name": "JavaScript",
          "level": 88
        },
        {
          "name": "Java",
          "level": 85
        },
        {
          "name": "Bash",
          "level": 98
        },
        {
          "name": "PyTorch",
          "level": 82
        },
        {
          "name": "Go",
          "level": 86
        },
        {
          "name": "Rust",
          "level": 69
        },
        {
          "name": "SQL",
          "level": 88
        }
      ]
    },
    {
      "category": "web_stack",
      "items": [
        {
          "name": "React",
          "level": 83
        },
        {
          "name": "Vite",
          "level": 88
        },
        {
          "name": "Firebase",
          "level": 83
        },
        {
          "name": "Node.js",
          "level": 86
        },
        {
          "name": "Next.js",
          "level": 68
        },
        {
          "name": "Supabase",
          "level": 83
        },
        {
          "name": "PostgreSQL",
          "level": 75
        },
        {
          "name": "MySQL",
          "level": 86
        }
      ]
    },
    {
      "category": "devops",
      "items": [
        {
          "name": "Docker",
          "level": 88
        },
        {
          "name": "Kubernetes",
          "level": 82
        },
        {
          "name": "Calico_CNI",
          "level": 70
        },
        {
          "name": "GNS3",
          "level": 79
        },
        {
          "name": "System Design",
          "level": 75
        }
      ]
    },
    {
      "category": "security",
      "type": "red",
      "items": [
        {
          "name": "Pentesting",
          "level": 87
        },
        {
          "name": "Networking",
          "level": 85
        },
        {
          "name": "Firewalls",
          "level": 80
        },
        {
          "name": "Metasploit",
          "level": 84
        },
        {
          "name": "Ethical Hacking",
          "level": 93
        }
      ]
    },
    {
      "category": "systems",
      "items": [
        {
          "name": "Linux/Unix",
          "level": 92
        },
        {
          "name": "Kernel_Dev",
          "level": 76
        },
        {
          "name": "Net_Stack",
          "level": 83
        },
        {
          "name": "Systemd",
          "level": 80
        }
      ]
    }
  ],
  "projects": [
    {
      "name": "lost_and_found_webapp",
      "desc": "Firebase-backed web app with real-time sync and full user auth flow.",
      "tags": [
        "firebase",
        "js",
        "react"
      ],
      "badge": "live",
      "url": "https://github.com/grim-sudo"
    }
  ],
  "achievements": [
    {
      "icon": "🔍",
      "label": "recon_operator",
      "desc": "Internal network scanning and full enumeration in isolated lab environments.",
      "type": "red"
    },
    {
      "icon": "🔥",
      "label": "web_deployer",
      "desc": "Shipped a Firebase-backed web app with real-time sync and user authentication.",
      "type": ""
    },
    {
      "icon": "⚙️",
      "label": "kernel_explorer",
      "desc": "Linux kernel modules and OS internals at the system call level.",
      "type": "red"
    },
    {
      "icon": "🛡",
      "label": "firewall_warden",
      "desc": "Automated firewall engine with live threat intel feed integration.",
      "type": ""
    },
    {
      "icon": "🐍",
      "label": "python_serpent",
      "desc": "Custom recon toolkit — port scanning, OS fingerprinting, JSON output.",
      "type": ""
    },
    {
      "icon": "🌐",
      "label": "net_phantom",
      "desc": "Deep knowledge of TCP/IP, subnetting and protocol-level packet analysis.",
      "type": "red"
    },
    {
      "icon": "☠️",
      "label": "container_breaker",
      "desc": "Explored container escape scenarios and Kubernetes privilege boundaries",
      "type": "red"
    },
    {
      "icon": "👾",
      "label": "packet_sniffer",
      "desc": "Deep packet inspection and traffic analysis using Wireshark and tcpdump.",
      "type": ""
    },
    {
      "icon": "🤖",
      "label": "automation_engineer",
      "desc": "Developed Python automation tools for reconnaissance and reporting.",
      "type": ""
    },
    {
      "icon": "🕵️",
      "label": "threat_hunter",
      "desc": "Investigated attack surfaces and vulnerabilities in controlled lab environments",
      "type": ""
    },
    {
      "icon": "🐧",
      "label": "arch_operator",
      "desc": "Daily-driver Arch Linux environment with custom kernel tuning and tooling.",
      "type": ""
    }
  ]
};