// ═══════════════════════════════════════
// GRIM PORTFOLIO — data.js
// Generated by admin.html on 3/9/2026, 12:50:39 PM
// ═══════════════════════════════════════

const GRIM_DATA = {
  "identity": {
    "handle": "GRIM",
    "realname": "Shefan Tharani",
    "role": "Systems Engineer // Security Researcher",
    "tagline": "Building infrastructure. Exploiting systems. Securing what matters.",
    "github": "grim-sudo",
    "platform": "Arch / Kali / Debian",
    "toolset": "BlackArch · Metasploit · Burp Suite",
    "shell": "zsh / bash",
    "location": "CLASSIFIED",
    "clearance": "CLASSIFIED",
    "available": true
  },
  "mission": {
    "overview": "Systems developer and security researcher focused on Linux infrastructure, container orchestration, and offensive security testing. Operates at the intersection of DevOps engineering and adversarial security.",
    "platforms": [
      "Arch Linux",
      "Kali Linux",
      "Debian",
      "BlackArch",
      "Ubuntu Server",
      "Unix Kernel"
    ],
    "focusAreas": [
      "Penetration Testing",
      "OSINT",
      "Network reconnaissance & enumeration",
      "Linux systems engineering & kernel dev",
      "Offensive security labs & CTF ops"
    ],
    "toolset": [
      "Metasploit",
      "Burp Suite",
      "Nmap",
      "Docker",
      "Kubernetes",
      "Shodan",
      "AMASS",
      "IPGhost",
      "Sherlock",
      "Zsteg",
      "SQLMAP",
      "Maltego",
      "TheHarvester",
      "gobuster",
      "Nikto"
    ]
  },
  "boot": {
    "lines": [
      {
        "t": "[  0.000000] Linux kernel 6.6.30-arch1 detected",
        "c": ""
      },
      {
        "t": "[  0.001201] Arch system profile loaded",
        "c": "ok"
      },
      {
        "t": "[  0.082410] BlackArch toolkit mounted — 2900 tools ready",
        "c": "ok"
      },
      {
        "t": "[  0.213800] Kali pentest modules loaded",
        "c": "ok"
      },
      {
        "t": "[  0.881100] NET: Registered PF_INET6 protocol family",
        "c": ""
      }
    ],
    "accessMessage": "ACCESS GRANTED"
  },
  "network": {
    "nodes": [
      {
        "id": "inet",
        "label": "INTERNET",
        "col": "#888888",
        "info": "External traffic. IDS monitored. Rate-limited."
      },
      {
        "id": "fw",
        "label": "FIREWALL",
        "col": "#ff3b3b",
        "info": "iptables + pfSense. 247 rules. DPI enabled."
      },
      {
        "id": "router",
        "label": "ROUTER",
        "col": "#00d4ff",
        "info": "BGP + OSPF. VLAN segmented. QoS active."
      },
      {
        "id": "dev",
        "label": "DEV",
        "col": "#00ff88",
        "info": "React, Firebase, Node.js dev cluster."
      },
      {
        "id": "sec",
        "label": "SEC",
        "col": "#ff3b3b",
        "info": "Pentest lab. Kali, Metasploit, Burp Suite."
      },
      {
        "id": "ops",
        "label": "DEVOPS",
        "col": "#00d4ff",
        "info": "K8s cluster. Docker, Calico, CI/CD."
      },
      {
        "id": "db",
        "label": "DB",
        "col": "#00ff88",
        "info": "Encrypted at rest. 6h backups."
      },
      {
        "id": "kali",
        "label": "KALI",
        "col": "#ff3b3b",
        "info": "Kali attack box. Air-gapped."
      },
      {
        "id": "k8s",
        "label": "K8S",
        "col": "#00d4ff",
        "info": "Kubernetes nodes. Calico enforced."
      },
      {
        "id": "mon",
        "label": "MON",
        "col": "#888888",
        "info": "Prometheus + Grafana + AlertManager."
      }
    ]
  },
  "socials": [
    {
      "platform": "github",
      "label": "GitHub",
      "url": "https://github.com/grim-sudo",
      "icon": "gi"
    },
    {
      "platform": "linkedin",
      "label": "LinkedIn",
      "url": "https://linkedin.com/in/shefan-tharani",
      "icon": "li"
    },
    {
      "platform": "discord",
      "label": "Discord",
      "url": "https://discord.com/users/563804599119773708",
      "icon": "di"
    },
    {
      "platform": "email",
      "label": "Email",
      "url": "mailto:shefantharani42@gmail.com",
      "icon": "em"
    }
  ],
  "skills": [
    {
      "category": "programming",
      "items": [
        {
          "name": "C",
          "level": 85
        },
        {
          "name": "Python",
          "level": 90
        },
        {
          "name": "JavaScript",
          "level": 88
        },
        {
          "name": "Java",
          "level": 85
        },
        {
          "name": "Bash",
          "level": 98
        },
        {
          "name": "Pytorch",
          "level": 82
        },
        {
          "name": "Go",
          "level": 86
        },
        {
          "name": "Rust",
          "level": 69
        },
        {
          "name": "SQL",
          "level": 88
        }
      ]
    },
    {
      "category": "web_stack",
      "items": [
        {
          "name": "React",
          "level": 83
        },
        {
          "name": "Vite",
          "level": 88
        },
        {
          "name": "Firebase",
          "level": 83
        },
        {
          "name": "Node.js",
          "level": 86
        },
        {
          "name": "Next.JS",
          "level": 68
        },
        {
          "name": "Supabase",
          "level": 83
        },
        {
          "name": "POSTGRES",
          "level": 75
        },
        {
          "name": "MYSQL",
          "level": 86
        }
      ]
    },
    {
      "category": "devops",
      "items": [
        {
          "name": "Docker",
          "level": 88
        },
        {
          "name": "Kubernetes",
          "level": 82
        },
        {
          "name": "Calico_CNI",
          "level": 70
        },
        {
          "name": "GNS3",
          "level": 79
        },
        {
          "name": "System Design",
          "level": 75
        }
      ]
    },
    {
      "category": "security",
      "type": "red",
      "items": [
        {
          "name": "Pentesting",
          "level": 87
        },
        {
          "name": "Networking",
          "level": 85
        },
        {
          "name": "Firewalls",
          "level": 80
        },
        {
          "name": "Metasploit",
          "level": 84
        },
        {
          "name": "Ethical Hacking",
          "level": 93
        }
      ]
    },
    {
      "category": "systems",
      "items": [
        {
          "name": "Linux/Unix",
          "level": 92
        },
        {
          "name": "Kernel_Dev",
          "level": 76
        },
        {
          "name": "Net_Stack",
          "level": 83
        },
        {
          "name": "Systemd",
          "level": 80
        }
      ]
    }
  ],
  "projects": [
    {
      "name": "lost_and_found_webapp",
      "desc": "Firebase-backed web app with real-time sync and full user auth flow.",
      "tags": [
        "firebase",
        "js",
        "react"
      ],
      "badge": "live",
      "url": "https://github.com/grim-sudo"
    }
  ],
  "achievements": [
    {
      "icon": "🔍",
      "label": "recon_operator",
      "desc": "Internal network scanning and full enumeration in isolated lab environments.",
      "type": "red"
    },
    {
      "icon": "🔥",
      "label": "web_deployer",
      "desc": "Shipped a Firebase-backed web app with real-time sync and user authentication.",
      "type": ""
    },
    {
      "icon": "⚙️",
      "label": "kernel_explorer",
      "desc": "Linux kernel modules and OS internals at the system call level.",
      "type": "red"
    },
    {
      "icon": "🛡",
      "label": "firewall_warden",
      "desc": "Automated firewall engine with live threat intel feed integration.",
      "type": ""
    },
    {
      "icon": "🐍",
      "label": "python_serpent",
      "desc": "Custom recon toolkit — port scanning, OS fingerprinting, JSON output.",
      "type": ""
    },
    {
      "icon": "🌐",
      "label": "net_phantom",
      "desc": "Deep knowledge of TCP/IP, subnetting and protocol-level packet analysis.",
      "type": "red"
    }
  ]
};